### ISSUE TITLE
nit: Docs say install v1.4.0 but latest is v1.5.0

### ISSUE THREAD

**Issue by anishkny** [jurassiscripts/velociraptor-dot-run#6]
First of kudos on an excellent tool and docs!

Minor nit:

The docs say install **v1.4.0** but latest is **v1.5.0**

## Actual
https://velociraptor.run/docs/installation/

<img width="852" alt="Screen Shot 2022-07-11 at 12 27 44 PM" src="https://user-images.githubusercontent.com/357499/178206491-707697c2-aeb8-4909-b6d7-9ae204075f80.png">

## Expected
https://deno.land/x/velociraptor

<img width="898" alt="Screen Shot 2022-07-11 at 12 28 55 PM" src="https://user-images.githubusercontent.com/357499/178206667-4b7dcd45-c48d-4759-8a7a-83f168c6fe0b.png">

## Side note

I am curious how the docs pull latest version number from the registry (that's where the bug is)

**Comment by anishkny** [comment]
Ahh looks like the following are decoupled:

* `https://github.com/jurassiscripts/velociraptor/releases` = `v1.4.0` (<-- docs are pulling this in `vrVersion`)
* `https://deno.land/x/velociraptor` = `v1.5.0`

**Comment by umbopepato** [comment]
Hey @anishkny, thank you so much for reporting this!
The deploy workflow of the website is automatically triggered by new GH releases on the main vr repo but apparently the last `conventional-github-releaser` run failed. I re-triggered it manually, it should be ok now 🙂

PS This will improve when we'll merge the new - even more automated - release workflows (see [CI auto](https://github.com/jurassiscripts/velociraptor/tree/feature/ci_auto))

**Comment by anishkny** [comment]
Indeed! Can confirm fixed in docs:

<img width="855" alt="Screen Shot 2022-07-11 at 12 43 19 PM" src="https://user-images.githubusercontent.com/357499/178208770-cfe4a959-ddf3-460d-a1e7-c7ec0522dfb1.png">

Fast work!
